### ISSUE TITLE
Browserify errors.

### ISSUE THREAD

**Issue by Serubin** [hyperapp/hyperapp#5]
Using the hello world code I get the following error from browserify:

```
> browserify -g uglifyify index.js | uglifyjs > bundle.js
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/seru/Share/Devel/Projects/Web/hyperapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)
    at js_error (eval at <anonymous> (/Users/seru/Share/Devel/Projects/Web/hyperapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)
    at croak (eval at <anonymous> (/Users/seru/Share/Devel/Projects/Web/hyperapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)
    at token_error (eval at <anonymous> (/Users/seru/Share/Devel/Projects/Web/hyperapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)
    at unexpected (eval at <anonymous> (/Users/seru/Share/Devel/Projects/Web/hyperapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)
    at expr_atom (eval at <anonymous> (/Users/seru/Share/Devel/Projects/Web/hyperapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2635:9)
    at maybe_unary (eval at <anonymous> (/Users/seru/Share/Devel/Projects/Web/hyperapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)
    at expr_ops (eval at <anonymous> (/Users/seru/Share/Devel/Projects/Web/hyperapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:24)
    at maybe_conditional (eval at <anonymous> (/Users/seru/Share/Devel/Projects/Web/hyperapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2837:20)
    at maybe_assign (eval at <anonymous> (/Users/seru/Share/Devel/Projects/Web/hyperapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2861:20
```

If I remove the uglify bit I get this:
```
> browserify index.js
import { app, html } from "hyperapp"
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

For reference, my index.js file:
```
import { app, html } from "hyperapp"
app({
   model: "Hello World!",                                                                             
    view: model =>  html`<h1>${model}</h1>`
})
```

**Comment by Serubin** [comment]
Using  `const { app, html } = require('hyperapp')` works fine.
So does not using uglify. I did note this comment from the uglifyjs2 repo: [issue #4000](https://github.com/mishoo/UglifyJS2/issues/1400#issuecomment-265184196)

**Comment by Serubin** [comment]
Ah, okay! Thank you. New to es6 :)

**Comment by jbucaran** [comment]
Haha, no worries. It took me like a year to remember all that.
